# Generated by Django 3.2.9 on 2021-11-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='제목')),
                ('singer', models.CharField(max_length=100, verbose_name='가수')),
                ('date', models.CharField(max_length=100, verbose_name='작성 날짜')),
                ('appraisal', models.TextField(verbose_name='한줄 평')),
            ],
        ),
    ]
