# Generated by Django 3.2.9 on 2021-11-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(max_length=100, verbose_name='작성 날짜'),
        ),
    ]
