# Generated by Django 3.2.9 on 2021-11-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='singer',
            field=models.CharField(max_length=100, verbose_name='가수명'),
        ),
    ]
