# Generated by Django 3.2.9 on 2021-11-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='제목')),
                ('singer', models.CharField(max_length=100, verbose_name='가수명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='한줄 평')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
